### ISSUE TITLE
[REQUEST] allow tzlocal>=5.1

### ISSUE THREAD

**Issue by BertLindeman** [SerBrynden/PiClock3#1]
**Is your feature request related to a problem? Please describe.**
Running  Raspbian GNU/Linux 10 (buster) with python version 3.7.3. There is no tzlocal version high enough for this python 

**Describe the solution you'd like**
Tested with version 5.1 on this system without problem.
**Describe alternatives you've considered**
Not really ready to upgrade this system to bookworm as I am not sure about the availability od a driver for the touchscreen.

**Additional context**

Can create a PullRequest to lower the tzlocal minimum from 5.2 to 5.1 
Let me know.

**Comment by SerBrynden** [comment]
No problem.  I made the change.
